# Generated by Django 3.1.5 on 2021-01-15 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_auto_20210115_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=150, null=True)),
                ('collection', models.ManyToManyField(related_name='collection_cards', to='cards.CardModel')),
                ('deck', models.ManyToManyField(related_name='deck_cards', to='cards.CardModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
