# Generated by Django 3.1.5 on 2021-01-14 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.IntegerField(choices=[(0, 'Spearman'), (1, 'Infantryman'), (2, 'Cavalryman'), (3, 'Missleman')])),
                ('rarity', models.IntegerField(choices=[(0, 'Common'), (1, 'Uncommon'), (2, 'Elite'), (3, 'Epic'), (4, 'Legendary'), (5, 'Mythic')])),
                ('attack', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('image', models.CharField(max_length=150, null=True, unique=True)),
                ('defaultInCollection', models.BooleanField(default=False)),
                ('defaultInDeck', models.BooleanField(default=False)),
                ('effect', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCardsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionCardsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
