# Generated by Django 3.1.5 on 2021-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210114_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='effect',
            field=models.IntegerField(choices=[], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
