# Generated by Django 3.1.5 on 2021-01-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20210114_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcardsmodel',
            name='card',
        ),
        migrations.RemoveField(
            model_name='deckcardsmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CollectionCardsModel',
        ),
        migrations.DeleteModel(
            name='DeckCardsModel',
        ),
    ]
