# Generated by Django 3.1.5 on 2021-02-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210115_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='rarity',
            field=models.IntegerField(choices=[(0, 'Common'), (1, 'Uncommon'), (2, 'Elite'), (3, 'Epic'), (4, 'Mythic')]),
        ),
    ]
