# Generated by Django 3.1.5 on 2021-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210217_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='image',
            field=models.CharField(default='baseCardImage.jpg', max_length=150),
        ),
    ]
