# Generated by Django 3.1.5 on 2021-03-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20210217_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
