# Generated by Django 3.2.5 on 2021-07-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20210301_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodel',
            name='effect',
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Unit')], default=0),
        ),
    ]
